# Imagen base Node.js
FROM node:20

# Carpeta de trabajo
WORKDIR /usr/src/app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto donde correrá la app React
EXPOSE 3000

# Comando para iniciar la app en modo desarrollo
CMD ["npm", "run", "dev"]
